{{- if .Values.interactive }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- include "chart.labels" . | indent 2}}
spec:
  {{- if eq .Values.serviceType "nodeport" }}
  type: 'NodePort'
  {{- else if eq .Values.serviceType "loadbalancer" }}
  type: 'LoadBalancer'
  {{- else}}
  type: 'ClusterIP'
  {{- end}}
  selector: 
    release: {{ .Release.Name }}
  ports:
    {{- range $index, $port := .Values.ports }}
    {{ $parts := split ":" $port }}
    - name: "{{ $parts._1 }}-port"
      protocol: 'TCP'
      port: {{ $parts._0 }}
      targetPort: {{ $parts._1 }}
      {{ if eq $.Values.serviceType "nodeport" }}
      nodePort: {{ $parts._0 }}
      {{ end }}
    {{- end}}
{{- end}}