apiVersion: batch/v1
kind: "Job"
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "runai.name" . }}
    chart: {{ template "runai.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "RunaiJob"
spec:
  template:
    metadata:
      annotations:
        project: {{ .Values.project }}
    spec:
      schedulerName: runai-scheduler
      restartPolicy: Never
      hostIPC: {{ .Values.hostIPC }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.gpus }}
          volumeMounts:
            {{- range $index, $volume := .Values.volumes}}
            {{ $parts := split ":" $volume }}
            - mountPath: {{ $parts._1 }}
              name: "volume-{{ $index }}"
            {{- end }}
      volumes:
        {{- range $index, $volume := .Values.volumes}}
        {{ $parts := split ":" $volume }}
          - name: "volume-{{ $index }}"
            hostPath: 
              path: {{ $parts._0 }}
              type: Directory
        {{- end }}




