apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itay-sts
spec:
  serviceName: jupyter
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      annotations:
        project: default
        user: john
      labels:
        app: jupyter
    spec:
      containers:
        - image: jupyter/scipy-notebook
          imagePullPolicy: Always
          command: ["start-notebook.sh"]
          name: quickstart
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "1"
      schedulerName: runai-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: itay-svc
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: itay-sts-0
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
