# Not using concat to support previous version of helm
{{- $combinedVolume := list }}
{{- range $volume := (.Values.volume | default list) }}
{{- $combinedVolume = append $combinedVolume $volume }}
{{- end}}
{{- range $volume := (.Values.volumeDefault | default list) }}
{{- $combinedVolume = append $combinedVolume $volume }}
{{- end}}
# Not using concat to support previous version of helm
{{- $combinedPorts := list }}
{{- range $port := (.Values.ports | default list) }}
{{- $combinedPorts = append $combinedPorts $port }}
{{- end}}
{{- range $port := (.Values.portsDefault | default list) }}
{{- $combinedPorts = append $combinedPorts $port }}
{{- end}}

apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: {{ .Release.Name }}
  annotations:
    image: "{{ .Values.image }}"
  labels:
    app: {{ template "mpijob.name" . }}
    chart: {{ template "mpijob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "MPIJob"
    project: {{ .Values.project }}
    {{- if .Values.user }}
    user: {{ .Values.user }}
    {{- end }}
    {{- if .Values.interactive }}
    priorityClassName: "build"
    {{- end}}
spec:
  {{- if .Values.node_type }}
  nodeSelector:
    run.ai/type: {{ .Values.node_type }}
  {{- end}}
  securityContext:
    {{- if .Values.runAsUser }}
    runAsUser: {{ .Values.runAsUser }}
    {{- end}}
    {{- if .Values.runAsGroup }}
    runAsGroup: {{ .Values.runAsGroup }}
  {{- end }}
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            project: {{ .Values.project }}
            {{- if .Values.user }}
            user: {{ .Values.user }}
            {{- end }}
        spec:
          {{- if .Values.node_type }}
          nodeSelector:
            run.ai/type: {{ .Values.node_type }}
          {{- end}}
          schedulerName: runai-scheduler
          containers:
            - image: "{{ .Values.image }}"
              name: mpi
              {{- if .Values.localImage}}
              imagePullPolicy: Never
              {{- else if .Values.alwaysPullImage }}
              imagePullPolicy: Always
              {{- end }}
              {{- if .Values.workingDir }}
              workingDir: {{ .Values.workingDir }}
              {{- end}}
              command:
              {{ range $index, $command := .Values.command }}
              - {{ quote $command }}
              {{- end}}
              args:
              {{ range $index, $arg := .Values.args }}
              - {{ quote $arg }}
              {{- end}}
              {{- if .Values.workingDir }}
              workingDir: {{ .Values.workingDir }}
              {{- end}}
              resources:
                requests:
                  {{- if .Values.cpu}}
                  cpu: {{ .Values.cpu }}
                  {{- end}}
                  {{- if .Values.memory}}
                  memory: {{ .Values.memory }}
                  {{- end }}
              volumeMounts:
                {{- range $index, $volume := $combinedVolume}}
                {{ $parts := split ":" $volume }}
                - mountPath: {{ $parts._1 }}
                  name: "volume-{{ $index }}"
                  {{- if eq $parts._2 "ro" }}
                  readOnly: true
                {{- end}}
                {{- end }}
                {{- if .Values.shm }}
                - mountPath: /dev/shm
                  name: dshm
                {{- end }}
              ports:
                {{- range $port := $combinedPorts}}
                # float will be the type when it's not quoted
                {{- if kindIs "float64" $port }}
                - protocol: 'TCP'
                  containerPort: {{$port}}
                {{- else }}
                {{ $parts := split ":" $port }}
                - protocol: 'TCP'
                  containerPort: {{ $parts._1 | default $parts._0 }}
                  {{- end}}
                {{- end}}
              env:
                # Not using concat to support previous version of helm
                {{- range $index, $env := .Values.environmentDefault }}
                {{ $parts := split "=" $env }}
                - name: {{ quote $parts._0 }}
                  value: {{ quote $parts._1}}
                {{- end }}
                {{- range $index, $env := .Values.environment }}
                {{ $parts := split "=" $env }}
                - name: {{ quote $parts._0 }}
                  value: {{ quote $parts._1}}
                {{- end }}
                - name: RUNAI_MPI_NUM_WORKERS
                  value: "{{ .Values.numProcesses }}"
          volumes:
            {{- range $index, $volume := $combinedVolume}}
            {{ $parts := split ":" $volume }}
            - name: "volume-{{ $index }}"
              hostPath:
                path: {{ $parts._0 }}
                type: Directory
            {{- end }}
            {{- if .Values.shm }}
            - name: dshm
              emptyDir:
                medium: Memory
    {{- end }}
    Worker:
      replicas: {{ .Values.numProcesses }}
      template:
        metadata:
          labels:
            project: {{ .Values.project }}
            {{- if .Values.user }}
            user: {{ .Values.user }}
            {{- end }}
        spec:
          {{- if .Values.node_type }}
          nodeSelector:
            run.ai/type: {{ .Values.node_type }}
          {{- end}}
          schedulerName: runai-scheduler
          containers:
            - image: "{{ .Values.image }}"
              name: mpi
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              resources:
                limits:
                  nvidia.com/gpu: {{ .Values.gpu}}
                requests:
                  {{- if .Values.cpu}}
                  cpu: {{ .Values.cpu }}
                  {{- end}}
                  {{- if .Values.memory}}
                  memory: {{ .Values.memory }}
                  {{- end }}
              env:
                # Not using concat to support previous version of helm
                {{- range $index, $env := .Values.environmentDefault }}
                {{ $parts := split "=" $env }}
                - name: {{ quote $parts._0 }}
                  value: {{ quote $parts._1}}
                {{- end }}
                {{- range $index, $env := .Values.environment }}
                {{ $parts := split "=" $env }}
                - name: {{ quote $parts._0 }}
                  value: {{ quote $parts._1}}
                {{- end }}
