
executors:
  runai-executor:
    docker:
      - image: runai/circleci-go 
      working_directory: /go/src/github.com/kubeflow/arena

version: 2.1
jobs:
  build:
    executor: runai-executor
    steps:
    - checkout
    - run: mkdir -p workspace/binaries
    - run:
        name: general-prep
        command: rm .env
    - run:
        name: build-mac
        command: |
          make cli-darwin-amd64
          tar -czvf darwin-amd64.tar.gz bin install-runai.sh charts
          mv darwin-amd64.tar.gz workspace/binaries
    - run: 
        name: build-linux
        command: |
          make cli-linux-amd64
          tar -czvf linux-amd64.tar.gz bin install-runai.sh charts
          mv linux-amd64.tar.gz workspace/binaries
    - persist_to_workspace:
        root: workspace
        paths:
          - binaries
  push:
    executor: runai-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: push
          command: |
            set -ex 
            hub release edit -a /tmp/workspace/binaries/darwin-amd64.tar.gz -a /tmp/workspace/binaries/linux-amd64.tar.gz -m "" v1.0.0

workflows:
  version: 2.1

  staging:
    jobs:
      - build: 
          name: build
      - push:
          name: push
          requires:
            - build
          filters:
            branches:
              only:
               - runai-master
