
executors:
  runai-executor:
    docker:
      - image: gcr.io/run-ai-staging/circleci-go:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    working_directory: /go/src/github.com/run-ai/runai-admin-cli

version: 2.1
orbs:
  slack: circleci/slack@4.1.1
jobs:
  test:
    executor: runai-executor
    steps:
    - checkout
    - run:
        name: run test
        command: |
          ./test.sh
    - slack/notify:
        channel: circleci
        event: fail
        template: basic_fail_1
  build:
    executor: runai-executor
    steps:
    - checkout
    - run: mkdir -p workspace/binaries
    - run:
        name: general-prep
        command: rm .env
    - restore_cache:
        keys:
          - runai-admin-cli-{{ .Branch }}-{{ checksum "go.sum" }}
    - run:
        name: build-mac
        command: |
          make cli-darwin-amd64
          tar --transform "s,bin/runai-adm,runai-adm," -czvf runai-admin-cli-darwin-amd64.tar.gz bin/runai-adm install-runai.sh VERSION
          mv runai-admin-cli-darwin-amd64.tar.gz workspace/binaries/runai-admin-cli-darwin-amd64.tar.gz
    - run: 
        name: build-linux
        command: |
          make cli-linux-amd64
          tar --transform "s,bin/runai-adm,runai-adm," -czvf runai-admin-cli-linux-amd64.tar.gz bin/runai-adm install-runai.sh VERSION
          mv runai-admin-cli-linux-amd64.tar.gz workspace/binaries/runai-admin-cli-linux-amd64.tar.gz
    - persist_to_workspace:
        root: workspace
        paths:
          - binaries
    - store_artifacts:
        path: workspace/binaries
    - save_cache:
        key: runai-admin-cli-{{ .Branch }}-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"
          - "/root/.cache/go-build"

  push:
    executor: runai-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: push
          command: |
            set -ex 
            echo $GCP_SERVICE_ACCOUNT >> ./key_file
            gcloud auth activate-service-account staging-ci@run-ai-staging.iam.gserviceaccount.com --key-file ./key_file
            gsutil cp /tmp/workspace/binaries/runai-admin-cli-darwin-amd64.tar.gz gs://admin-cli-artifacts/<<pipeline.git.revision>>/runai-admin-cli-darwin-amd64.tar.gz
            gsutil cp /tmp/workspace/binaries/runai-admin-cli-linux-amd64.tar.gz gs://admin-cli-artifacts/<<pipeline.git.revision>>/runai-admin-cli-linux-amd64.tar.gz
            # Update latest version for branch
            echo <<pipeline.git.revision>> > ./latest
            gsutil cp ./latest gs://admin-cli-artifacts/branch-versions/<<pipeline.git.branch>>
  release:
    executor: runai-executor
    steps:
      - checkout
      - run:
          name: get-packages
          command: |
            set -ex
            mkdir -p /tmp/packages
            echo $GCP_SERVICE_ACCOUNT >> ./key_file
            gcloud auth activate-service-account staging-ci@run-ai-staging.iam.gserviceaccount.com --key-file ./key_file
            gsutil cp gs://admin-cli-artifacts/<<pipeline.git.revision>>/runai-admin-cli-darwin-amd64.tar.gz /tmp/packages/runai-admin-cli-darwin-amd64.tar.gz
            gsutil cp gs://admin-cli-artifacts/<<pipeline.git.revision>>/runai-admin-cli-linux-amd64.tar.gz /tmp/packages/runai-admin-cli-linux-amd64.tar.gz
      - run:
          name: update-version
          command: |
            set -ex
            mkdir darwin
            mkdir linux
            tar -C darwin -zxvf /tmp/packages/runai-admin-cli-darwin-amd64.tar.gz
            tar -C linux -zxvf /tmp/packages/runai-admin-cli-linux-amd64.tar.gz
            echo <<pipeline.git.tag>> > darwin/VERSION
            echo <<pipeline.git.tag>> > linux/VERSION
            cd darwin
            tar -czvf runai-admin-cli-<<pipeline.git.tag>>-darwin-amd64.tar.gz runai-adm install-runai.sh VERSION
            cd ../linux
            tar -czvf runai-admin-cli-<<pipeline.git.tag>>-linux-amd64.tar.gz runai-adm install-runai.sh VERSION
            cd ../
      - run:
          name: upload-version
          command: |
            hub release edit -a darwin/runai-admin-cli-<<pipeline.git.tag>>-darwin-amd64.tar.gz#runai-admin-cli-<<pipeline.git.tag>>-darwin-amd64.tar.gz -a linux/runai-admin-cli-<<pipeline.git.tag>>-linux-amd64.tar.gz#runai-admin-cli-<<pipeline.git.tag>>-linux-amd64.tar.gz -m "" <<pipeline.git.tag>>

workflows:
  version: 2.1

  staging:
    jobs:
      - build: 
          name: build
      - test:
          name: test
      - push:
          name: push
          requires:
            - build
            - test
          filters:
            branches:
              only:
               - master
               # regular expression to match for version branches. any branch that represents a version: v1.0.0, v1.0.0-rc, v1.x.x, .etc
               - /v.+?\..+?\..+/
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          name: release
          filters:
            branches:
              ignore: /.*/  
            tags:
              only: /^v.*/
