{{- if (not .Values.enableGangScheduler) -}}
{{- if (not .Values.hasGangScheduler) -}}
{{- if .Values.useTensorboard }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tfjob.fullname" . }}
  labels:
    app: {{ template "tfjob.name" . }}
    chart: {{ template "tfjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "TFJob"
    role: tensorboard
spec:
  template:
    metadata:
      labels:
        app: {{ template "tfjob.name" . }}
        chart: {{ template "tfjob.chart" . }}
        release: {{ .Release.Name }}
        role: tensorboard
    spec:
      {{- if .Values.ps }}
      {{- if .Values.hasGangScheduler }}
      {{- if .Values.enableGangScheduler }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- end }}
      {{- end }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                  - {{ template "tfjob.name" . }}
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: release
                operator: In
                values: 
                  - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: tf-replica-index
                operator: In
                values: 
                  - "0"
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: tf-replica-type
                operator: In
                values: 
                  - "worker"
            topologyKey: kubernetes.io/hostname
      volumes:
        - hostPath:
            path: "{{ .Values.hostLogPath }}"
          name: training-logs-volume
      containers:
      - name: tensorboard      
        command: ["tensorboard", "--logdir", "/output/training_logs",  "--host",  "0.0.0.0"]
        image: "{{ .Values.tensorboardImage }}"
        imagePullPolicy: {{ .Values.tensorboardImagePullpolicy }}
        ports:
        - containerPort: 6006
        volumeMounts:
        - mountPath: /output/training_logs
          name: training-logs-volume
{{- end }}
{{- end }}
{{- end }}