{{- if eq .Values.enableIstio true }}
{{- if eq .Values.modelServiceExists false }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.servingName }}"
spec:
  hosts:
  - "{{ .Values.servingName }}"
  http:
  - route:
    - destination:
        host: {{ .Values.servingName }}
        subset: v{{ .Values.servingVersion }}
        port:
          number: {{ .Values.rest_api_port }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.servingName }}
spec:
  host: {{ .Values.servingName }}
  subsets:
  - name: v{{ .Values.servingVersion }}
    labels:
      serviceVersion: "{{ .Values.servingVersion }}"
{{- end }}
{{- end }}